# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
    ]
