# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('context', models.TextField(max_length=280, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u4fe1\u606f',
                'verbose_name_plural': '\u8bc4\u8bba\u4fe1\u606f',
            },
        ),
    ]
