# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
    ]
